export const NEWS_DATA_AVAILABLE = 'NEWS_DATA_AVAILABLE';
export const NEWS_DATA_UN_AVAILABLE = 'NEWS_DATA_UN_AVAILABLE';

export const CATEGORY_DATA_AVAILABLE = 'CATEGORY_DATA_AVAILABLE';
export const CATEGORY_DATA_UN_AVAILABLE = 'CATEGORY_DATA_UN_AVAILABLE';